package com.abcrentals.binu.thankachan.enums;

public enum EthnicityEnum {
	NOT_AVAILABLE,
	AMERICAN_INDIAN_OR_ALASKA_NATIVE,
	ASIAN,
	BLACK_OR_AFRICAN_AMERICAN,
	HISPANIC_OR_LATINO,
	NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER,
	WHITE
	
}
